name: LearningTests
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Запуск тестов
    runs-on: ubuntu-latest
    steps:
            
          CI/CD github actions: https://github.com/${{ github.repository }}/actions
          https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Пройти проверки тестов
      uses: actions-hub/stylelint@master
      env:        
        PATTERN: "**/*.css"
